# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.TextField(help_text=b'The value for the added property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(choices=[(b'definition', b'Definition'), (b'description', b'Description'), (b'note', b'Note'), (b'system', b'System')], help_text=b"The name of the added property; e.g., 'Description'.", max_length=50, verbose_name=b'Property Type'),
        ),
        migrations.AlterField(
            model_name='term',
            name='label',
            field=models.CharField(help_text=b'The human-readable name of the term.', max_length=255),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(help_text=b'The name or key that uniquely identifies the term within the vocabulary.', max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='order',
            field=models.IntegerField(blank=True, help_text=b'The preferred order for viewing the term in the vocabulary.', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='vocab_list',
            field=models.ForeignKey(help_text=b'The vocabulary that the term needs to be added to.', on_delete=django.db.models.deletion.CASCADE, to='controlled_vocabularies.Vocabulary', verbose_name=b'Vocabulary'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='definition',
            field=models.TextField(blank=True, help_text=b'A brief statement of the meaning of the vocabulary.'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='label',
            field=models.CharField(help_text=b'The human-readable name of the vocabulary.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='maintainer',
            field=models.CharField(help_text=b'The person responsible for creating and updating the vocabulary.', max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='maintainerEmail',
            field=models.CharField(help_text=b'E-mail address of maintainer.', max_length=50, verbose_name=b'Maintainer E-mail'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(help_text=b'The name or key that uniquely identifies the vocabulary.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='order',
            field=models.CharField(choices=[(b'name', b'name'), (b'label', b'label'), (b'order', b'order')], help_text=b'The preferred order for viewing the UNTL list of controlled vocabularies.', max_length=10),
        ),
    ]
