# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-09 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0002_auto_20180924_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.TextField(help_text='The value for the added property.'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(choices=[('definition', 'Definition'), ('description', 'Description'), ('note', 'Note'), ('system', 'System')], help_text="The name of the added property; e.g., 'Description'.", max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='term_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlled_vocabularies.Term', verbose_name='Term'),
        ),
        migrations.AlterField(
            model_name='term',
            name='label',
            field=models.CharField(help_text='The human-readable name of the term.', max_length=255),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(help_text='The name or key that uniquely identifies the term within the vocabulary.', max_length=50),
        ),
        migrations.AlterField(
            model_name='term',
            name='order',
            field=models.IntegerField(blank=True, help_text='The preferred order for viewing the term in the vocabulary.', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='vocab_list',
            field=models.ForeignKey(help_text='The vocabulary that the term needs to be added to.', on_delete=django.db.models.deletion.CASCADE, to='controlled_vocabularies.Vocabulary', verbose_name='Vocabulary'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='definition',
            field=models.TextField(blank=True, help_text='A brief statement of the meaning of the vocabulary.'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='label',
            field=models.CharField(help_text='The human-readable name of the vocabulary.', max_length=255),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='maintainer',
            field=models.CharField(help_text='The person responsible for creating and updating the vocabulary.', max_length=50),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='maintainerEmail',
            field=models.CharField(help_text='E-mail address of maintainer.', max_length=50, verbose_name='Maintainer E-mail'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(help_text='The name or key that uniquely identifies the vocabulary.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='order',
            field=models.CharField(choices=[('name', 'name'), ('label', 'label'), ('order', 'order')], help_text='The preferred order for viewing the UNTL list of controlled vocabularies.', max_length=10),
        ),
    ]
