# Generated by Django 2.2.19 on 2021-03-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabularies', '0003_auto_20191209_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_name',
            field=models.CharField(choices=[('description', 'Description'), ('note', 'Note'), ('system', 'System')], help_text="The name of the added property; e.g., 'Description'.", max_length=50, verbose_name='Property Type'),
        ),
    ]
